# Tracker config

root_folder: '/netscratch/jeetmal/videos/capture_22_02_2025/Shalini/videos'
save_folder: '/netscratch/jeetmal/output/mvfga/Shalini/metrical_tracker/'
optimize_shape: true
optimize_jaw: true
optimize_neck: false
undistort: true
begin_frames: 15
alpha_map : false
keyframes: [ 16, 17 ]
